version: '3.8'

services:
  spark:
      image: bitnami/spark:3.1.2
      user: root # Run container as root container: https://docs.bitnami.com/tutorials/work-with-non-root-containers/
      hostname: spark
      #networks:
      #    - default_net
      environment:
          - SPARK_MODE=master
          - SPARK_RPC_AUTHENTICATION_ENABLED=no
          - SPARK_RPC_ENCRYPTION_ENABLED=no
          - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
          - SPARK_SSL_ENABLED=no
      ports:
          - "8181:8080"
          - "7077:7077"
  jupyter-spark:
    image: jupyter/pyspark-notebook:latest
    #networks:
    #    - default_net
    ports:
      - "8888:8888"
      #- "4040-4080:4040-4080"
    volumes:
      - ./notebooks/work:/home/jovyan/work/
